<a href="https://colab.research.google.com/github/exeliuioar/MachineLearningLab/blob/main/Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

df_cirr = pd.read_csv('cirrhosis.csv')
df_house = pd.read_csv('USA_Housing.csv')

print(df_cirr.describe(include='all'))
print(df_house.describe(include='all'))

                ID       N_Days Status             Drug           Age  Sex  \
count   418.000000   418.000000    418              312    418.000000  418   
unique         NaN          NaN      3                2           NaN    2   
top            NaN          NaN      C  D-penicillamine           NaN    F   
freq           NaN          NaN    232              158           NaN  374   
mean    209.500000  1917.782297    NaN              NaN  18533.351675  NaN   
std     120.810458  1104.672992    NaN              NaN   3815.845055  NaN   
min       1.000000    41.000000    NaN              NaN   9598.000000  NaN   
25%     105.250000  1092.750000    NaN              NaN  15644.500000  NaN   
50%     209.500000  1730.000000    NaN              NaN  18628.000000  NaN   
75%     313.750000  2613.500000    NaN              NaN  21272.500000  NaN   
max     418.000000  4795.000000    NaN              NaN  28650.000000  NaN   

       Ascites Hepatomegaly Spiders Edema   Bilirubin  Choleste

In [3]:
df_cirr.drop('ID', axis=1, inplace=True)

for col in df_cirr.columns:
    if df_cirr[col].dtype == 'object':
        df_cirr[col] = df_cirr[col].fillna(df_cirr[col].mode()[0])
    else:
        df_cirr[col] = df_cirr[col].fillna(df_cirr[col].mean())

df_house.drop('Address', axis=1, inplace=True)
df_house['Price_Class'] = (df_house['Price'] > df_house['Price'].median()).astype(int)
df_house.drop('Price', axis=1, inplace=True)

In [4]:

from sklearn.preprocessing import LabelEncoder, StandardScaler

le = LabelEncoder()
cat_cols = df_cirr.select_dtypes(include='object').columns
for col in cat_cols:
    df_cirr[col] = le.fit_transform(df_cirr[col])

scaler = StandardScaler()

X_cirr = df_cirr.drop('Status', axis=1)
y_cirr = df_cirr['Status']
X_cirr_scaled = scaler.fit_transform(X_cirr)

X_house = df_house.drop('Price_Class', axis=1)
y_house = df_house['Price_Class']
X_house_scaled = scaler.fit_transform(X_house)

In [5]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

def execute_model(X, y):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    model = LogisticRegression(max_iter=1000)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(confusion_matrix(y_test, predictions))
    print(classification_report(y_test, predictions))

execute_model(X_cirr_scaled, y_cirr)
execute_model(X_house_scaled, y_house)

[[55  1 10]
 [ 5  0  2]
 [16  0 37]]
              precision    recall  f1-score   support

           0       0.72      0.83      0.77        66
           1       0.00      0.00      0.00         7
           2       0.76      0.70      0.73        53

    accuracy                           0.73       126
   macro avg       0.49      0.51      0.50       126
weighted avg       0.70      0.73      0.71       126

[[664  67]
 [ 75 694]]
              precision    recall  f1-score   support

           0       0.90      0.91      0.90       731
           1       0.91      0.90      0.91       769

    accuracy                           0.91      1500
   macro avg       0.91      0.91      0.91      1500
weighted avg       0.91      0.91      0.91      1500

